# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Ahmed M. ElKholy - PhD Student & Power Systems Engineer"
title_separator          : "|"
name                     : &name "Ahmed M. ElKholy"
description              : &description "PhD Student at MPEI | Assistant Lecturer at Tanta University | Expert in FACTS Devices, Industrial Protection & Decarbonization | MATLAB, Python, C, R, STM32 Developer"
url                      : https://ahmelkholy.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "ahmelkholy/ahmelkholy.github.io"
teaser                   : "bio-photo.jpg" # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : true # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "enabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : true #change to true to add link to talkmap on talks page
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" # "master", "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['Ahmed Elkholy', 'ahmed_elkholy@f-eng.tanta.edu.eg', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  path                   : # blank (default) uses feed.xml

# SEO Related
google_site_verification : "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" # Enhanced - from Google Search Console
bing_site_verification   : "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" # Enhanced - from Bing Webmaster Tools
alexa_site_verification  :
yandex_site_verification : "XXXXXXXXXXXXXXXX" # Enhanced - from Yandex Webmaster

# Social Sharing
twitter:
  username               : &twitter "ahmelkholy"
facebook:
  username               : "ahm.m.elkholy"
  app_id                 :
  publisher              :
og_image                 : "bio-photo.jpg"  # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : "Person" # Person or Organization (defaults to Person)
  name                   : "Ahmed M. ElKholy" # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://www.linkedin.com/in/ahmelkholy/"
    - "https://scholar.google.com/citations?user=KbZs8_AAAAAJ&hl=en"
    - "https://github.com/ahmelkholy"
    - "https://www.researchgate.net/profile/Ahmed-Elkholy-7"
    - "https://orcid.org/0000-0002-1834-1175"
    - "https://www.youtube.com/@ahmelkholy"
    - "https://facebook.com/ahm.m.elkholy"


# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-XXXXXXXXXX" # Replace with your Google Analytics 4 ID
    anonymize_ip         : false # true, false (default)

# Google Ads / AdSense Configuration
# Uncomment and replace with your actual AdSense client ID when ready
# google_ad_client         : "ca-pub-XXXXXXXXXXXXXXXXX" # Replace with your AdSense client ID
# google_ad_slot_responsive: "XXXXXXXXX" # Replace with your responsive ad slot ID
# google_ad_slot_article   : "XXXXXXXXX" # Replace with your in-article ad slot ID
# google_ad_slot_sidebar   : "XXXXXXXXX" # Replace with your sidebar ad slot ID
# google_ad_slot_footer    : "XXXXXXXXX" # Replace with your footer ad slot ID


# Site Author
author:
  name             : "Ahmed M. ElKholy"
  avatar           : "profile.png"
  bio              : "PhD Student at MPEI | Assistant Lecturer at Tanta University | Expert in FACTS Devices, Industrial Protection & Decarbonization | Software Developer (MATLAB, Python, C, R, STM32)"
  location         : "Moscow, Russia / Tanta, Egypt"
  employer         : "MPEI / Tanta University"
  pubmed           :
  googlescholar    : "https://scholar.google.com/citations?user=KbZs8_AAAAAJ&hl=en"
  email            : "ahm_elkholy@outlook.com"
  researchgate     : "https://www.researchgate.net/profile/Ahmed-Elkholy-7"
  uri              : "https://ahmelkholy.github.io"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : "ahm.m.elkholy"
  foursquare       :
  github           : "ahmelkholy"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      :
  lastfm           :
  linkedin         : "ahmelkholy"
  orcid            : "https://orcid.org/0000-0002-1834-1175"
  pinterest        :
  soundcloud       :
  stackoverflow    :
  steam            :
  tumblr           :
  twitter          : "ahmelkholy"
  vine             :
  weibo            :
  xing             :
  youtube          : "https://www.youtube.com/@ahmelkholy"
  wikipedia        :
  scopus           : "https://www.scopus.com/authid/detail.uri?authorId=57202189065"
  webofscience     : "https://www.webofscience.com/wos/author/record/AAS-9757-2020"
  zotero           : "https://zotero.org/ahmelkholy"
  sciprofiles      : "https://sciprofiles.com/profile/amelkholy"
  university       : "https://tdb2.tanta.edu.eg/staff/ahmelkholy"


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true
  # _projects temp
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Europe/Moscow #America/Los_Angeles # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
